- name: Copy docker-compose file to edge device
  template:
    src: docker-compose.yml.j2
    dest: /tmp/docker-compose.yml
    mode: '0644'

- name: Pull docker-compose images
  command:
    cmd: bash -c "cd /tmp && docker-compose pull"

- name: Start docker-compose
  command:
    cmd: docker-compose -f /tmp/docker-compose.yml up -d 
