---
version: '2'

services:
        mosquitto:
                build: ./mosquitto
                expose:
                        - "1883" #mqtt port

        forwarder:
                build: ./forwarder
                stdin_open: true
                tty: true
                expose:
                        - "1883"
                ports:
                        - "1883:1883" #because i'm not getting acks from remote broker?
                depends_on: 
                          - mosquitto
                volumes:
                        - /:/edge
                          #command:  >
                          #sh -c "cd /edge/forwarder &&
                          #    python forwarder.py"

        # video:
        #         build: ./video
        #         privileged: true
        #         stdin_open: true
        #         environment:
        #                 DISPLAY: 'true'
        #         tty: true
        #         depends_on:
        #                 - mosquitto
        #                 - forwarder
        #         volumes:
        #                 - /:/edge
        #         command: >
        #                 sh -c "cd /edge/video &&
        #                 python3 capture.py"


        detector: 
                build: ./detector
                privileged: true
                stdin_open: true
                environment:
                        -  DISPLAY
                tty: true
                depends_on: 
                        - mosquitto
                volumes: 
                        - /edge:/edge
                        - /tmp:/tmp
                
        
        thermal:
                build: ./thermal
                stdin_open: true
                tty: true
                depends_on:
                          - mosquitto
                volumes:
                        - /:/edge
                          #command:  >
                          #sh -c "cd /edge/thermal && 
                          #    python thermalDetector.py"

        # distance:
        #         build: ./distance
        #         stdin_open: true
        #         tty: true
        #         depends_on:
        #                   - mosquitto
        #         volumes:
        #                 - /:/edge
        #                   #command:  >
        #                   #sh -c "cd /edge/distance &&
        #                   #    python distanceDetector.py"

           
