development:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/mask_detector_development"}}

test:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/mask_detector_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/mask_detector_production"}}
